### ISSUE TITLE
After updating MD-80 with X-Updater, all my aircrafts and sceneries disappeared

### ISSUE THREAD

**Issue by Hal34** [steptosky/x-updater-doc#1]
Hello,
Here is a really big catastrophe.
After updating my Rotate MD-80 using X-Updater, I started X-Plane and a message told that I should update X-Plane from the installation page. So I did it (without asking for the beta version) and then I flew with MD-80, without looking at where my other planes were.

Then I wanted to fly with my ZIBO 737-800, but I discovered that all my planes, purchased and freeware, were gone.

I quit and relaunched X-Plane, but the problem persists.
Yet my aircrafts folders were all still in the Aircraft file of X-Plane.
Yes, except… that on closer inspection, I realize that the aircraft files were there, but all empty!
Same for all my sceneries!

Possible explanation:
When I launched X-Updater, I had to “browse the folder” and I thought I had to indicate the main X-Plane folder.
It was then that a "verification" window indicated to me "zero files".
>> Did X-Updater emptied all my files?

Main question:
>> Is it possible to reverse or do I have to reinstall my hundreds of stages and planes?
>> Otherwise, what can I do?
Do you understand what happened?

Thanks for your help, I'm desperate.
And thank you again.

**Comment by Pancir** [comment]
You selected a wrong folder and used "fresh" checkbox, the x-updater informed you that all files in the selected folder will be deleted if you press ok. 
You had to select folder of you plane.

This repository is not for support. If you want support you have to make a ticket in our tickets system. https://tickets.flightfactor.aero/

**Comment by Hal34** [comment]
Thank you very much for your clear and useful answer.

**Comment by Hal34** [comment]
Maybe the message in the window of X-Updater could be more clear to avoid such a result.
